# Generated by Django 2.1.15 on 2020-02-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master_config',
            fields=[
                ('company_code', models.CharField(max_length=100, primary_key='True', serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('company_mobile', models.CharField(max_length=200)),
                ('company_address', models.CharField(max_length=100)),
            ],
        ),
    ]
